siteName: "Stephen Hawkes"
collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    format: "yaml-frontmatter"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "layout", label: "Layout", widget: "string", default: "post" }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "body", label: "Content", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: ""
    files:
      - file: "about.md"
        label: "About"
        name: "about"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "layout", label: "Layout", widget: "string", default: "page" }
          - { name: "body", label: "Content", widget: "markdown" }
      - file: "contact.html"
        label: "Contact"
        name: "contact"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "layout", label: "Layout", widget: "string", default: "page" }
          - { name: "body", label: "Content", widget: "markdown" }

media:
  folder: "assets/uploads"