input: .
output: .
siteName: "Stephen Hawkes"
media:
  input: assets/uploads
  output: assets/uploads
collections:
  posts:
    label: "Blog Posts"
    path: _posts
    create: true
    fields:
      title:
        label: "Title"
        type: string
      date:
        label: "Date"
        type: datetime
      layout:
        label: "Layout"
        type: string
        default: "post"
      tags:
        label: "Tags"
        type: list
      body:
        label: "Content"
        type: markdown
  pages:
    label: "Static Pages"
    files:
      about:
        label: "About"
        path: about.md
        fields:
          title:
            label: "Title"
            type: string
          layout:
            label: "Layout"
            type: string
            default: "page"
          body:
            label: "Content"
            type: markdown
      contact:
        label: "Contact"
        path: contact.html
        fields:
          title:
            label: "Title"
            type: string
          layout:
            label: "Layout"
            type: string
            default: "page"
          body:
            label: "Content"
            type: markdown
