media:
  input: img
  output: /img
  rename: safe

settings:
  hide: true
  content:
    merge: true
  commit:
    identity: user

content:
  - name: posts
    label: Blog posts
    type: collection
    path: _posts
    create: true
    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: false
    view:
      fields: [title, published, date, tags]
      primary: title
      sort: [date, title]
      search: [title, summary, tags]
      default:
        sort: date
        order: desc
    fields:
      - name: published
        label: Published
        type: boolean
        default: false
      - name: date
        label: Date
        type: date
        required: true
      - name: title
        label: Title
        type: string
        required: true
      - name: summary
        label: Summary
        type: text
        required: true
        options:
          maxlength: 240
      - name: tags
        label: Tags
        type: string
        list:
          max: 6
      - name: see_also
        label: See also
        type: reference
        options:
          collection: posts
          multiple: true
          max: 3
          search: "title,summary,tags"
          value: "{path}"
          label: "{primary}"
      - name: image
        label: Social image
        type: image
        required: false
      - name: body
        label: Body
        type: rich-text
