remote_theme: hawkz/Balzac-for-Jekyll

title:            Stephen Hawkes
tagline:          He has kept news
description:      Stephen Hawkes personal blog
canonical: http://stephenhawkes.com/

# Owner/author information
owner:
  name:           Stephen Hawkes
  avatar:         avatar.png
  bio:            MD at The Developer Society
  email:          steve@dev.ngo
  twitter:        hawkz
  github:         hawkz
  instagram:      hawkz
  location:       "Birmingham, UK"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_GB

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Work
    url: https://www.dev.ngo/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
